"""Recompute Estimator — predict duration and row count before running.

Uses historical run statistics from ``recompute_run_stats`` and
``recompute_dependencies`` to estimate how long a recompute will take
and how many rows it will produce, before actually executing it.

Also provides data freshness checks to skip recompute when no new data
has arrived since the last run.

Usage::

    from market.analysis.recompute_estimator import RecomputeEstimator

    # Estimate before running
    est = RecomputeEstimator.estimate_function("recompute_scores")
    # → {"estimated_duration_s": 45.2, "estimated_rows": 4800,
    #    "confidence": "high", "last_run_at": "2026-08-17T..."}

    # Estimate for a selective recompute trigger
    est = RecomputeEstimator.estimate_trigger("stock_prices")
    # → {"total_estimated_duration_s": 120.5, "total_estimated_rows": 15000,
    #    "functions": [...], "can_skip": ["recompute_fear_greed"]}

    # Check if data is fresh enough to skip
    skip = RecomputeEstimator.should_skip("recompute_scores", "stock_prices")
    # → True if no new stock_prices data since last run
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime, timedelta
from typing import Any

from sqlalchemy import func, select, text
from sqlalchemy.orm import Session

from market.db.engine import get_sessionmaker
from market.db.models import RecomputeDependency, RecomputeRunStats

logger = logging.getLogger(__name__)

# Minimum runs before we trust the average
_MIN_RUNS_FOR_ESTIMATE = 3
# If data hasn't changed in this many hours, skip recompute
_DEFAULT_STALE_THRESHOLD_HOURS = 24

# Recompute schedule intervals (hours between runs)
_RECOMPUTE_INTERVALS: dict[str, float] = {
    "recompute_technical_indicators": 24.0,
    "recompute_scores": 24.0,
    "recompute_relationship_matrix": 48.0,
    "recompute_fear_greed": 6.0,
    "recompute_stock_personality": 168.0,  # weekly
    "recompute_ml_labels": 24.0,
    "recompute_market_regimes": 24.0,
    "recompute_weights": 168.0,  # weekly
    "recompute_holiday_effects": 720.0,  # monthly
    "recompute_instrument_profiles": 168.0,  # weekly
    "recompute_cross_market_coefficients": 168.0,
    "recompute_dcc_garch": 720.0,  # monthly
    "recompute_seasonal_patterns": 720.0,
    "recompute_macro_correlation": 168.0,
    "recompute_causal_relationships": 168.0,
    # recompute_satellite_correlation: not yet implemented (phantom function)
    "recompute_astronacci_cycles": 24.0,
    "recompute_cross_market": 48.0,
}


class RecomputeEstimator:
    """Estimate recompute duration and rows from historical data."""

    @staticmethod
    def estimate_function(
        function_name: str,
        session: Session | None = None,
    ) -> dict[str, Any]:
        """Estimate duration and rows for a single recompute function.

        Reads pre-computed prediction from ``recompute_predictions`` table
        (generated by RecomputeAnalyzer). Returns empty estimate with
        source='no_data' if no prediction exists — does NOT compute on-the-fly.

        Returns dict with:
        - predicted_duration_s: predicted runtime in seconds
        - predicted_rows: predicted number of output rows
        - confidence: 'high' (≥0.8), 'medium' (≥0.5), 'low' (≥0.2), 'none' (0)
        - confidence_score: numeric 0.0 to 1.0
        - analysis_method: how prediction was computed
        - sample_size: number of historical runs used
        - last_run_at: when last executed
        - last_duration_s: last actual duration
        - last_rows: last actual row count
        - run_count: total historical runs
        - source: 'db_prediction' or 'no_data'
        """
        own_session = False
        if session is None:
            try:
                session = get_sessionmaker()()
                own_session = True
            except Exception:
                return RecomputeEstimator._empty_estimate(function_name)

        try:
            # 1. Try reading pre-computed prediction from DB
            from market.analysis.recompute_analyzer import RecomputeAnalyzer

            db_pred = RecomputeAnalyzer.get_prediction(function_name, session=session)
            if db_pred:
                # Get last run info for context
                last_run_row = session.execute(
                    select(RecomputeRunStats)
                    .where(
                        RecomputeRunStats.function_name == function_name,
                        RecomputeRunStats.status == "completed",
                    )
                    .order_by(RecomputeRunStats.started_at.desc())
                    .limit(1)
                ).scalar_one_or_none()

                last_dur = float(last_run_row.duration_seconds) if last_run_row and last_run_row.duration_seconds else None
                last_rows = last_run_row.rows_affected if last_run_row else None

                # Convert confidence score to label
                cs = db_pred["confidence_score"]
                if cs >= 0.8:
                    confidence = "high"
                elif cs >= 0.5:
                    confidence = "medium"
                elif cs >= 0.2:
                    confidence = "low"
                else:
                    confidence = "none"

                return {
                    "function_name": function_name,
                    "predicted_duration_s": db_pred["predicted_duration_s"],
                    "predicted_rows": db_pred["predicted_rows"],
                    "predicted_tickers": db_pred.get("predicted_tickers"),
                    "confidence": confidence,
                    "confidence_score": cs,
                    "analysis_method": db_pred["analysis_method"],
                    "sample_size": db_pred["sample_size"],
                    "last_run_at": last_run_row.started_at.isoformat() if last_run_row else None,
                    "last_duration_s": round(last_dur, 1) if last_dur else None,
                    "last_rows": last_rows,
                    "run_count": db_pred["sample_size"],
                    "source": "db_prediction",
                }

            # 2. No DB prediction available — return empty estimate
            #    Do NOT compute on-the-fly. Run RecomputeAnalyzer first to generate predictions.
            logger.debug(
                "RecomputeEstimator: no DB prediction for '%s'. "
                "Run RecomputeAnalyzer.analyze_all() to generate predictions.",
                function_name,
            )
            return RecomputeEstimator._empty_estimate(function_name)
        except Exception as e:
            logger.debug("RecomputeEstimator: estimate_function failed: %s", e)
            return RecomputeEstimator._empty_estimate(function_name)
        finally:
            if own_session:
                session.close()

    @staticmethod
    def estimate_trigger(
        data_source: str,
        session: Session | None = None,
    ) -> dict[str, Any]:
        """Estimate total duration and rows for a selective recompute trigger.

        Returns dict with:
        - data_source: the triggered data source
        - total_estimated_duration_s: sum of all affected functions
        - total_estimated_rows: sum of estimated rows
        - functions: list of per-function estimates
        - can_skip: list of functions that can be skipped (data not stale)
        - confidence: overall confidence level
        """
        from market.analysis.recompute_graph import RecomputeGraph

        own_session = False
        if session is None:
            try:
                session = get_sessionmaker()()
                own_session = True
            except Exception:
                return {"data_source": data_source, "functions": [], "total_estimated_duration_s": None}

        try:
            affected = RecomputeGraph.get_affected_functions(data_source, session=session)

            functions = []
            total_dur = 0.0
            total_rows = 0.0
            can_skip = []
            confidence_levels = []

            for fn_name in affected:
                est = RecomputeEstimator.estimate_function(fn_name, session=session)

                # Check if we can skip (data not stale)
                should_skip = RecomputeEstimator.should_skip(fn_name, data_source, session=session)
                if should_skip:
                    can_skip.append(fn_name)
                    est["will_skip"] = True
                else:
                    est["will_skip"] = False
                    dur = est.get("predicted_duration_s") or est.get("estimated_duration_s")
                    rows = est.get("predicted_rows") or est.get("estimated_rows")
                    if dur:
                        total_dur += dur
                    if rows:
                        total_rows += rows

                functions.append(est)
                confidence_levels.append(est["confidence"])

            # Overall confidence
            if all(c == "high" for c in confidence_levels):
                overall_confidence = "high"
            elif all(c == "none" for c in confidence_levels):
                overall_confidence = "none"
            elif any(c == "high" for c in confidence_levels):
                overall_confidence = "medium"
            else:
                overall_confidence = "low"

            return {
                "data_source": data_source,
                "total_estimated_duration_s": round(total_dur, 1) if total_dur else None,
                "total_estimated_rows": round(total_rows) if total_rows else None,
                "functions": functions,
                "can_skip": can_skip,
                "functions_to_run": len(affected) - len(can_skip),
                "functions_to_skip": len(can_skip),
                "confidence": overall_confidence,
            }
        except Exception as e:
            logger.debug("RecomputeEstimator: estimate_trigger failed: %s", e)
            return {"data_source": data_source, "functions": [], "total_estimated_duration_s": None}
        finally:
            if own_session:
                session.close()

    @staticmethod
    def should_skip(
        function_name: str,
        data_source: str,
        stale_threshold_hours: float = _DEFAULT_STALE_THRESHOLD_HOURS,
        session: Session | None = None,
    ) -> bool:
        """Check if a recompute function can be skipped (data not stale).

        Uses the ``recommendation`` column from ``recompute_dependencies``
        as the primary signal. Falls back to legacy freshness check if
        the recommendation is not available.

        A function can be skipped if:
        1. recommendation == 'SKIP' (data fresh, next_run_at in future)
        2. OR: last run < 1 hour ago (avoid duplicate runs)
        3. AND: input data hasn't changed since last run

        Args:
            function_name: Recompute function name.
            data_source: Input data source to check freshness.
            stale_threshold_hours: Skip if data is older than this (default 24h).
            session: Optional SQLAlchemy session.

        Returns:
            True if the function can be skipped.
        """
        own_session = False
        if session is None:
            try:
                session = get_sessionmaker()()
                own_session = True
            except Exception:
                return False  # Can't check → don't skip

        try:
            # 1. Check recommendation from recompute_dependencies (primary)
            dep_row = session.execute(
                text(
                    "SELECT recommendation, next_run_at, last_data_changed_at, last_run_at "
                    "FROM recompute_dependencies "
                    "WHERE function_name = :fn LIMIT 1"
                ),
                {"fn": function_name},
            ).first()

            if dep_row:
                recommendation, next_run_at, last_data_changed, dep_last_run = dep_row

                if recommendation == "RUN_NOW":
                    return False  # Explicitly flagged to run
                if recommendation == "SKIP":
                    # Check if next_run_at has passed
                    now = datetime.now(UTC)
                    if next_run_at is not None:
                        if isinstance(next_run_at, str):
                            next_run_at = datetime.fromisoformat(next_run_at)
                        if next_run_at.tzinfo is None:
                            next_run_at = next_run_at.replace(tzinfo=UTC)
                        if now >= next_run_at:
                            return False  # Scheduled time has passed → don't skip
                    # Verify data source is valid before skipping
                    data_last_updated = RecomputeEstimator._get_data_last_updated(data_source, session)
                    if data_last_updated is None:
                        return False  # Can't verify data source → don't skip
                    return True  # Data fresh, next_run in future → skip

            # 2. Fallback: legacy freshness check
            # Get last run time for this function
            last_run = session.execute(
                select(RecomputeRunStats.started_at)
                .where(
                    RecomputeRunStats.function_name == function_name,
                    RecomputeRunStats.status == "completed",
                )
                .order_by(RecomputeRunStats.started_at.desc())
                .limit(1)
            ).scalar_one_or_none()

            if last_run is None:
                # Never run → can't skip
                return False

            now = datetime.now(UTC)

            # If last run is very recent (< 1 hour), skip to avoid duplicate runs
            hours_since_run = (now - last_run.replace(tzinfo=UTC)).total_seconds() / 3600
            if hours_since_run < 1.0:
                return True  # Ran less than 1 hour ago → skip

            # Check data freshness in the source table
            data_last_updated = RecomputeEstimator._get_data_last_updated(data_source, session)
            if data_last_updated is None:
                # Can't determine → don't skip
                return False

            # If data was updated AFTER last run → don't skip (new data to process)
            if data_last_updated.replace(tzinfo=UTC) > last_run.replace(tzinfo=UTC):
                return False

            # Data hasn't changed since last run → check staleness threshold
            hours_since_data = (now - data_last_updated.replace(tzinfo=UTC)).total_seconds() / 3600
            if hours_since_data > stale_threshold_hours:
                return False  # Data is stale → should recompute anyway

            return True  # Data is fresh and unchanged → skip

        except Exception as e:
            logger.debug("RecomputeEstimator: should_skip failed: %s", e)
            return False
        finally:
            if own_session:
                session.close()

    @staticmethod
    def _get_data_last_updated(
        data_source: str,
        session: Session,
    ) -> datetime | None:
        """Get the timestamp of the most recent data in a source table.

        Tries common timestamp column names: timestamp, date, created_at,
        updated_at, as_of, tanggal, event_date, report_date.
        """
        # Map of table → timestamp column
        ts_columns = {
            "stock_prices": "timestamp",
            "fundamental_data": "date",
            "fundamental_quarterly": "date",
            "macro_data": "date",
            "foreign_flow": "date",
            "policy_events": "event_date",
            "external_events": "tanggal",
            "seasonal_patterns": "created_at",
            "earnings_calendar": "earnings_date",
            "exchange_holidays": "holiday_date",
            "satellite_observations": "observed_at",
            "causal_relationships": "created_at",
            "scores": "as_of",
            "fear_greed": "date",
            "news_sentiment": "published_at",
        }

        col = ts_columns.get(data_source, "updated_at")

        try:
            result = session.execute(
                text(f"SELECT MAX({col}) FROM {data_source}")
            ).scalar()
            if result is None:
                # Try created_at as secondary timestamp column
                result = session.execute(
                    text(f"SELECT MAX(created_at) FROM {data_source}")
                ).scalar()
            return result
        except Exception:
            return None

    @staticmethod
    def record_run(
        function_name: str,
        started_at: datetime,
        completed_at: datetime | None = None,
        duration_seconds: float | None = None,
        rows_affected: int | None = None,
        tickers_processed: int | None = None,
        tickers_skipped: int | None = None,
        incremental: bool = False,
        status: str = "completed",
        error_message: str | None = None,
        trigger_id: int | None = None,
        session: Session | None = None,
    ) -> bool:
        """Record a recompute run in recompute_run_stats and update aggregates.

        Should be called after every recompute execution (success or failure).
        """
        own_session = False
        if session is None:
            session = get_sessionmaker()()
            own_session = True

        try:
            # Insert run stats record
            run = RecomputeRunStats(
                function_name=function_name,
                trigger_id=trigger_id,
                started_at=started_at,
                completed_at=completed_at,
                duration_seconds=duration_seconds,
                rows_affected=rows_affected,
                tickers_processed=tickers_processed,
                tickers_skipped=tickers_skipped,
                incremental=incremental,
                status=status,
                error_message=error_message,
            )
            session.add(run)

            # Update aggregate stats on recompute_dependencies
            # Update all rows for this function_name
            deps = session.execute(
                select(RecomputeDependency)
                .where(RecomputeDependency.function_name == function_name)
            ).scalars().all()

            now = datetime.now(UTC)
            for dep in deps:
                # Shift last_run_at to previous_run_at before overwriting
                if dep.last_run_at is not None:
                    dep.previous_run_at = dep.last_run_at
                dep.last_run_at = now
                dep.last_duration_seconds = duration_seconds
                dep.last_rows_affected = rows_affected
                dep.run_count = (dep.run_count or 0) + 1

                # Set next_run_at based on interval (default 24h)
                interval_h = _RECOMPUTE_INTERVALS.get(function_name, 24.0)
                dep.next_run_at = now + timedelta(hours=interval_h)

                # Set recommendation based on status
                if status == "completed":
                    dep.recommendation = "SKIP"
                    dep.recommendation_reason = (
                        f"Completed at {now.isoformat()}, next run at {dep.next_run_at.isoformat()}"
                    )
                elif status == "failed":
                    dep.recommendation = "RUN_NOW"
                    dep.recommendation_reason = f"Last run failed: {error_message or 'unknown error'}"
                elif status == "skipped":
                    # Keep existing recommendation, just update next_run_at
                    pass

                # Recompute rolling average from last 10 runs
                recent_runs = session.execute(
                    select(RecomputeRunStats.duration_seconds, RecomputeRunStats.rows_affected)
                    .where(
                        RecomputeRunStats.function_name == function_name,
                        RecomputeRunStats.status == "completed",
                    )
                    .order_by(RecomputeRunStats.started_at.desc())
                    .limit(10)
                ).all()

                if recent_runs:
                    durations = [r[0] for r in recent_runs if r[0] is not None]
                    rows_list = [r[1] for r in recent_runs if r[1] is not None]
                    if durations:
                        dep.avg_duration_seconds = sum(durations) / len(durations)
                    if rows_list:
                        dep.avg_rows_affected = sum(rows_list) / len(rows_list)

            session.commit()
            return True
        except Exception as e:
            logger.error("RecomputeEstimator: record_run failed: %s", e)
            session.rollback()
            return False
        finally:
            if own_session:
                session.close()

    @staticmethod
    def get_run_history(
        function_name: str,
        limit: int = 20,
        session: Session | None = None,
    ) -> list[dict[str, Any]]:
        """Get historical run stats for a function."""
        own_session = False
        if session is None:
            session = get_sessionmaker()()
            own_session = True

        try:
            rows = session.execute(
                select(RecomputeRunStats)
                .where(RecomputeRunStats.function_name == function_name)
                .order_by(RecomputeRunStats.started_at.desc())
                .limit(limit)
            ).scalars().all()

            return [
                {
                    "id": r.id,
                    "started_at": r.started_at.isoformat() if r.started_at else None,
                    "completed_at": r.completed_at.isoformat() if r.completed_at else None,
                    "duration_seconds": float(r.duration_seconds) if r.duration_seconds else None,
                    "rows_affected": r.rows_affected,
                    "tickers_processed": r.tickers_processed,
                    "tickers_skipped": r.tickers_skipped,
                    "incremental": r.incremental,
                    "status": r.status,
                    "error_message": r.error_message,
                }
                for r in rows
            ]
        except Exception as e:
            logger.debug("RecomputeEstimator: get_run_history failed: %s", e)
            return []
        finally:
            if own_session:
                session.close()

    @staticmethod
    def _empty_estimate(function_name: str) -> dict[str, Any]:
        return {
            "function_name": function_name,
            "predicted_duration_s": None,
            "predicted_rows": None,
            "confidence": "none",
            "confidence_score": 0.0,
            "analysis_method": "none",
            "sample_size": 0,
            "last_run_at": None,
            "last_duration_s": None,
            "last_rows": None,
            "run_count": 0,
            "source": "no_data",
        }
